# Generated by Django 5.1.1 on 2024-09-17 14:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImageModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoanerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'loaner',
                'verbose_name_plural': 'loaners',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_actor', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('platform', models.CharField(blank=True, choices=[('playstation', 'Playstation'), ('xbox', 'XBox'), ('nintendo_switch', 'Nintendo Switch'), ('pc', 'PC')], default=None, max_length=150, null=True)),
                ('category', models.CharField(blank=True, choices=[('movies', 'Movies'), ('books', 'Books'), ('games', 'Games'), ('action_figures', 'Action Figures')], default=None, max_length=150, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('dvd', 'DVD'), ('bluray', 'Bluray'), ('digital', 'Digital'), ('book', 'Book'), ('comics', 'Comics'), ('kindle', 'Kindle')], default=None, max_length=150, null=True)),
                ('launch_date', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('loaned', 'Loaned')], default=None, max_length=150, null=True)),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.itemimagemodel')),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.loanermodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usermodel')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoanHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.itemmodel')),
                ('loan_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_date', to='catalog.loanermodel')),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner_name', to='catalog.loanermodel')),
                ('return_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_date', to='catalog.loanermodel')),
            ],
            options={
                'verbose_name': 'history',
                'ordering': ('-loan_date',),
            },
        ),
    ]
